### ISSUE TITLE
夫妻商贷还款金额计算

### ISSUE THREAD

**Issue by Kannnnng** [zkqiang/hangzhou-house-guide#1]
> 通过商业贷款能贷多少钱，取决于你的还款能力，常见的评判标准是你的月收入。银行会让你提供公司开具的工资证明、工资银行卡的流水等材料来进行审核。一般要求你的月收入必须大于每月还款额的 2 倍，也就是你想申请每月还 1 万元的贷款，必须提供每月 2 万元的收入证明（当然有些银行可能要求更高）。

如果是夫妻的话，一个人的月收入小于还款金额的两倍，两个人的月收入之和大于还款金额的两倍，这样申请房贷的时候可以以夫妻二人月收入之和来计算还款金额和可以申请到的最终房贷金额吗？

**Comment by zkqiang** [comment]
可以，只要房子是夫妻两个人名义就行

**Comment by Kannnnng** [comment]
您好，我已收到您的来信，并会尽快答复，祝好。闫守康
